apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: mta
  labels:
    app.kubernetes.io/name: api-gateway
spec:
  selector:
    app.kubernetes.io/name: api-gateway
  ports:
    - name: http
      port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: mta
  labels:
    app.kubernetes.io/name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: mta/api-gateway:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mta-secrets
                  key: API_SECRET_KEY
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: mta-config
                  key: DEBUG
            - name: GRPC_AUTH_HOST
              valueFrom:
                configMapKeyRef:
                  name: mta-config
                  key: GRPC_AUTH_HOST
            - name: GRPC_TASK_HOST
              valueFrom:
                configMapKeyRef:
                  name: mta-config
                  key: GRPC_TASK_HOST
            - name: GRPC_TRACKER_HOST
              valueFrom:
                configMapKeyRef:
                  name: mta-config
                  key: GRPC_TRACKER_HOST
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
