apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
  - databases/auth-db.yaml
  - databases/task-db.yaml
  - databases/tracker-db.yaml
  - databases/mq.yaml
  - services/auth-service.yaml
  - services/task-service.yaml
  - services/tracker-service.yaml
  - services/tracker-worker.yaml
  - gateways/api-gateway.yaml
  - gateways/web-gateway.yaml
  - ui/web-ui.yaml
