scalar DateTime

enum Status {
    STATUS_TODO_UNSPECIFIED
    STATUS_IN_PROGRESS
    STATUS_DONE
    STATUS_SCRAPED
}

type EmptyType {
    success: Boolean!
}

type Profile {
    firstName: String!
    lastName: String!
    email: String!
    dateJoined: DateTime!
    lastLogin: DateTime!
}

type RetrieveItem {
    id: ID!
    description: String!
    status: Status!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type ListItem {
    count: Int!
    results: [RetrieveItem!]!
}

type Count {
    todo: Int!
    inProgress: Int!
    done: Int!
    scraped: Int!
    total: Int!
}

type DayAnalytics {
    hour: String!
    counts: Count!
}

type WeekAnalytics {
    weekday: String!
    counts: Count!
}

type MonthAnalytics {
    week: String!
    counts: Count!
}

type YearAnalytics {
    month: String!
    counts: Count!
}

type Query {
    profile: Profile!
    logout: EmptyType!
    listItem(limit: Int, offset: Int, ordering: String, status: Status): ListItem!
    retrieveItem(id: ID!): RetrieveItem!
    dayAnalytics(date: DateTime!): [DayAnalytics!]!
    weekAnalytics(date: DateTime!): [WeekAnalytics!]!
    monthAnalytics(date: DateTime!): [MonthAnalytics!]!
    yearAnalytics(date: DateTime!): [YearAnalytics!]!
}

type Mutation {
    passwordChange(currentPassword: String!, newPassword: String!, confirmPassword: String!): EmptyType!
    createItem(description: String!): RetrieveItem!
    updateItem(id: ID!, description: String, status: Status): RetrieveItem!
    destroyItem(id: ID!): EmptyType!
}
