"""Initial migration

Revision ID: df23ab6392ea
Revises: 
Create Date: 2026-06-30 22:07:21.293496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df23ab6392ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_item_audit',
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_item_audit_created_at'), 'tracker_item_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_tracker_item_audit_task_id'), 'tracker_item_audit', ['task_id'], unique=False)
    op.create_index(op.f('ix_tracker_item_audit_updated_at'), 'tracker_item_audit', ['updated_at'], unique=False)
    op.create_index(op.f('ix_tracker_item_audit_user_id'), 'tracker_item_audit', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_item_audit_user_id'), table_name='tracker_item_audit')
    op.drop_index(op.f('ix_tracker_item_audit_updated_at'), table_name='tracker_item_audit')
    op.drop_index(op.f('ix_tracker_item_audit_task_id'), table_name='tracker_item_audit')
    op.drop_index(op.f('ix_tracker_item_audit_created_at'), table_name='tracker_item_audit')
    op.drop_table('tracker_item_audit')
    # ### end Alembic commands ###
